/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.ObraDAO;
import entity.Obra;
import entity.Usuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import org.joda.time.Instant;
import table.ObraAtualizarTableModel;
import table.ObraColumnModel;

/**
 *
 * @author Alex
 */
public class DialogEmprestimo extends javax.swing.JDialog {

    ObraDAO dao = new ObraDAO();
    static List<Obra> listaDeObra = new ArrayList<>();

    public static void DefineDadosEAjustesNajTable() {
        tbAtualizarObra.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = tbAtualizarObra.getFontMetrics(tbAtualizarObra.getFont());
        tbAtualizarObra.setColumnModel(new ObraColumnModel(fm));
        tbAtualizarObra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbAtualizarObra.setModel(new ObraAtualizarTableModel(listaDeObra));
    }

    /**
     * Creates new form DialogAtualizarObra
     */
    public DialogEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbDataDevolucao.setText(dataAtual.toDateTime().plusDays((int) spDias.getValue()).toString("dd/MM/yyyy"));
        lbUsuario.setText("");
        lbEmail.setText("");
        lbFone.setText("");
        //tfTitulo.requestFocus();
    }

    public static void setObraNaLista(Obra obra) {
        listaDeObra.add(obra);
        DefineDadosEAjustesNajTable();
    }

    public static void setUsuario(Usuario u) {
        usuario = u;
        setDados();
    }

    private static void setDados() {
        if (usuario != null) {
            if (usuario.getFoto().length > 0) {
                ImageIcon img = new ImageIcon(usuario.getFoto());
                lbFoto.setIcon(redimensionaImageIcon(img));
            }
            lbUsuario.setText(usuario.getNome());
            lbEmail.setText(usuario.getListEmail() != null ? usuario.getListEmail().get(0).getEmail() : "");
            lbFone.setText(usuario.getListTelefone() != null ? usuario.getListTelefone().get(0).getTelefone() : "");
        }
    }
    Instant dataAtual = new Instant();
    static Usuario usuario;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAtualizarObra = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btEmprestimo = new javax.swing.JButton();
        btVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btAlterarUsuario = new javax.swing.JButton();
        btSelecionarObra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spDias = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        lbDataDevolucao = new javax.swing.JLabel();
        lbDataDevolucao1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbFone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Obra");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 4));

        tbAtualizarObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbAtualizarObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAtualizarObraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAtualizarObra);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btEmprestimo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emprestimo.png"))); // NOI18N
        btEmprestimo.setText("Emprestar");
        btEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestimoActionPerformed(evt);
            }
        });

        btVoltar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        btVoltar1.setText("Voltar");
        btVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEmprestimo, btVoltar1});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEmprestimo, btVoltar1});

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Obras:");

        btAlterarUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        btAlterarUsuario.setText("Selecionar Usuário");
        btAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarUsuarioActionPerformed(evt);
            }
        });

        btSelecionarObra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSelecionarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Book-icon.png"))); // NOI18N
        btSelecionarObra.setText("Selecionar Obra");
        btSelecionarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarObraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Usuário:");

        lbUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbUsuario.setText("Fulano da Silva");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Devolução:");

        spDias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        spDias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(15), Integer.valueOf(0), null, Integer.valueOf(1)));
        spDias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spDiasStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("dias");

        lbDataDevolucao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbDataDevolucao.setText("dd/MM/yyyy");

        lbDataDevolucao1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbDataDevolucao1.setText("Data de Devolução:");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 154));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbFoto)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbFoto)
                .addGap(0, 141, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Fone:");

        lbEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbEmail.setText("Fulano da Silva");

        lbFone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbFone.setText("Fulano da Silva.............................................................");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 146, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spDias, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(lbDataDevolucao1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDataDevolucao))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btSelecionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbFone))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbEmail))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbUsuario)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbFone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSelecionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(spDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDataDevolucao1)
                        .addComponent(lbDataDevolucao))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spDiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spDiasStateChanged
        lbDataDevolucao.setText(dataAtual.toDateTime().plusDays((int) spDias.getValue()).toString("dd/MM/yyyy"));
    }//GEN-LAST:event_spDiasStateChanged

    private void btSelecionarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarObraActionPerformed
        new DialogSelecionarObra(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btSelecionarObraActionPerformed

    private void btAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarUsuarioActionPerformed
        new DialogAdicionarUsuario(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btAlterarUsuarioActionPerformed

    private void btVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltar1ActionPerformed

    private void btEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestimoActionPerformed
        dispose();
    }//GEN-LAST:event_btEmprestimoActionPerformed

    private void tbAtualizarObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAtualizarObraMouseClicked
        //        try {
            //            int rowIndex = tbAtualizarObra.getSelectedRow();
            //            if (rowIndex == -1) {
                //                JOptionPane.showMessageDialog(this, "Selecione a Obra a ser Atualizada!!!");
                //                return;
                //            }
            //            obra = new ObraAtualizarTableModel(listaDeObra).get(rowIndex);
            //        } catch (IndexOutOfBoundsException e) {
            //            DefineDadosEAjustesNajTable();
            //        }
    }//GEN-LAST:event_tbAtualizarObraMouseClicked

    
     private static ImageIcon redimensionaImageIcon(ImageIcon icon) {
        int height = icon.getIconHeight();
        int width = icon.getIconWidth();
        double alturaFinal = 141.0;
        double larguraFinal = 126.0;
        if (height > width) {
            if (height > alturaFinal) {
                double altura = alturaFinal / height;
                larguraFinal = width * altura;
            } else {
                double altura = height / alturaFinal;
                larguraFinal = width * altura;
            }
        } else {
            if (height > 126) {
                double largura = larguraFinal / width;
                alturaFinal = height * largura;
            } else {
                double largura = width / larguraFinal;
                alturaFinal = height * largura;
            }
        }
        icon.setImage(icon.getImage().getScaledInstance((int) larguraFinal, (int) alturaFinal, 100));
        return icon;
    }
    
    
//    private boolean pesquisa() {
//        try {
////            if (tfTitulo.getText().isEmpty()) {
////                JOptionPane.showMessageDialog(this, "Digite sua pesquisa.");
////                return false;
////            }
//            switch (cbOpcaoPesquisa.getSelectedIndex()) {
//                case 0:
//                    listaDeObra = dao.consulta(tfTitulo.getText());
////                    return verifica(listaDeObra);
//                    break;
//                case 1:
//                    listaDeObra = dao.consultaAutor(tfTitulo.getText());
////                    return verifica(listaDeObra);
//                    break;
//                case 2:
//                    listaDeObra = dao.consultaIsbn(tfTitulo.getText());
////                    return verifica(listaDeObra);
//                    break;
//                case 3:
//                    try {
//                        listaDeObra = dao.consultaPorCodigo(Integer.parseInt(tfTitulo.getText()));
//                    } catch (NumberFormatException e) {
//                        JOptionPane.showMessageDialog(this, "Favor digite somente números.");
//                        return false;
//                    }
////                    return verifica(listaDeObra);
//                break;
//                case 4:
//                    listaDeObra = dao.consultaAssunto(tfTitulo.getText());
////                    return verifica(listaDeObra);
//                    break;
//            }
//        } catch (SQLException | NameException ex) {
//            return false;
//        }
//        return false;
//    }
//    private boolean verifica(List<Obra> lista) {
//        if (lista.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "A busca não encontrou nenhum resultado.");
//            return false;
//        }
//        return true;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEmprestimo dialog = new DialogEmprestimo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarUsuario;
    private javax.swing.JButton btEmprestimo;
    private javax.swing.JButton btSelecionarObra;
    private javax.swing.JButton btVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDataDevolucao;
    private javax.swing.JLabel lbDataDevolucao1;
    public static javax.swing.JLabel lbEmail;
    public static javax.swing.JLabel lbFone;
    public static javax.swing.JLabel lbFoto;
    public static javax.swing.JLabel lbUsuario;
    private javax.swing.JSpinner spDias;
    public static javax.swing.JTable tbAtualizarObra;
    // End of variables declaration//GEN-END:variables
}
