/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author Bya
 */
public class FrmTelaPrincipal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FrmTelaPrincipal
     */
    JLabel rotuloHorario = new JLabel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy   "
            + "HH:mm");
    Timer timer;

    public FrmTelaPrincipal() {
        timer = new Timer(500, this);
        timer.setRepeats(true);
        timer.start();
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Dialog", Font.PLAIN, 20)));
        initComponents();
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource().equals(timer)) {
            this.relogioDigital.setText(sdf.format(new Date(System.currentTimeMillis())));
            this.relogioDigital.setFont(new Font("Dialog", Font.PLAIN, 20));
            this.relogioDigital.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        relogioDigital = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btGerenciarUsuario = new javax.swing.JButton();
        btGerenciarObra = new javax.swing.JButton();
        btEmprestimo = new javax.swing.JButton();
        btDevolução = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGerenciamento = new javax.swing.JMenu();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuItemObra = new javax.swing.JMenuItem();
        menuItemEditora = new javax.swing.JMenuItem();
        menuItemAutor = new javax.swing.JMenuItem();
        menuItemOperador = new javax.swing.JMenuItem();
        menuItemGerenciamentoAssunto = new javax.swing.JMenuItem();
        menuEmprestimo = new javax.swing.JMenu();
        menuDevolução = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        relogioDigital.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        relogioDigital.setText("Relógio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relogioDigital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relogioDigital)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        btGerenciarUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btGerenciarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user-icon.png"))); // NOI18N
        btGerenciarUsuario.setText("Gerenciador Usuario");
        btGerenciarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarUsuarioActionPerformed(evt);
            }
        });

        btGerenciarObra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btGerenciarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Book-icon.png"))); // NOI18N
        btGerenciarObra.setText("Gerenciador Obras");
        btGerenciarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarObraActionPerformed(evt);
            }
        });

        btEmprestimo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orientacao_preventiva.png"))); // NOI18N
        btEmprestimo.setText("Emprestimo");

        btDevolução.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btDevolução.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/archive-icon.png"))); // NOI18N
        btDevolução.setText("Devolução");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGerenciarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerenciarObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDevolução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btDevolução, btEmprestimo, btGerenciarObra, btGerenciarUsuario});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGerenciarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btGerenciarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btDevolução, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btDevolução, btEmprestimo, btGerenciarObra, btGerenciarUsuario});

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        btSair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1404967476_Exit.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capturar.PNG"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        menuGerenciamento.setText("Gerenciamento");
        menuGerenciamento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        menuItemUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemUsuario.setText("Gerenciamento De Usuario");
        menuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuarioActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemUsuario);

        menuItemObra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemObra.setText("Gerenciamento De Obra");
        menuItemObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemObraActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemObra);

        menuItemEditora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemEditora.setText("Gerenciamento De Editora");
        menuItemEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditoraActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemEditora);

        menuItemAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemAutor.setText("Gerenciamento De Autor");
        menuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAutorActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemAutor);

        menuItemOperador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemOperador.setText("Gerenciamento De Operador");
        menuItemOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOperadorActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemOperador);

        menuItemGerenciamentoAssunto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuItemGerenciamentoAssunto.setText("Gerenciamento De Assunto");
        menuItemGerenciamentoAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciamentoAssuntoActionPerformed(evt);
            }
        });
        menuGerenciamento.add(menuItemGerenciamentoAssunto);

        jMenuBar1.add(menuGerenciamento);

        menuEmprestimo.setText("Realizar Empréstimo");
        menuEmprestimo.setToolTipText("Clique para realizar um novo empréstimo");
        menuEmprestimo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuBar1.add(menuEmprestimo);

        menuDevolução.setText("Realizar Devolução");
        menuDevolução.setToolTipText("Clique para realizar a devolução do livro");
        menuDevolução.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuBar1.add(menuDevolução);

        menuRelatorio.setText("Relatorios");
        menuRelatorio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem5.setText("Relatorio Mensal");
        menuRelatorio.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem6.setText("Relatorio Anual");
        menuRelatorio.add(jMenuItem6);

        jMenuBar1.add(menuRelatorio);

        menuSobre.setText("Sobre");
        menuSobre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGerenciarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarUsuarioActionPerformed
        DialogGerenciadorUsuario telaUsuario = new DialogGerenciadorUsuario(null, true);
        telaUsuario.setVisible(true);
    }//GEN-LAST:event_btGerenciarUsuarioActionPerformed

    private void btGerenciarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarObraActionPerformed
        DialogGerenciadorObra telaObra = new DialogGerenciadorObra(new javax.swing.JFrame(), true);
        telaObra.setVisible(true);
    }//GEN-LAST:event_btGerenciarObraActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void menuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuarioActionPerformed
        DialogGerenciadorUsuario telaUsuario = new DialogGerenciadorUsuario(null, true);
        telaUsuario.setVisible(true);
    }//GEN-LAST:event_menuItemUsuarioActionPerformed

    private void menuItemObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemObraActionPerformed
        DialogGerenciadorObra telaObra = new DialogGerenciadorObra(new javax.swing.JFrame(), true);
        telaObra.setVisible(true);
    }//GEN-LAST:event_menuItemObraActionPerformed

    private void menuItemEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditoraActionPerformed
        DialogGerenciadorEditora telaEditora = new DialogGerenciadorEditora(new javax.swing.JFrame(), true);
        telaEditora.setVisible(true);
    }//GEN-LAST:event_menuItemEditoraActionPerformed

    private void menuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAutorActionPerformed
        DialogGerenciadorAutor telaAutor = new DialogGerenciadorAutor(new javax.swing.JFrame(), true);
        telaAutor.setVisible(true);
    }//GEN-LAST:event_menuItemAutorActionPerformed

    private void menuItemOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOperadorActionPerformed
        DialogGerenciadorOperador telaOperador = new DialogGerenciadorOperador(this, true);
        telaOperador.setVisible(true);
    }//GEN-LAST:event_menuItemOperadorActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        JOptionPane.showMessageDialog(null, "Este software faz parte do projeto de extensão Biblioteca das escolas municipais em transformação"
                + "\n" + "Ele foi desenvolvido no Institudo Federal de Santa Catarina e têm como principal objetivo "
                + "\n" + "auxiliar nas atividades básicas realizadas em uma biblioteca educacional!");
    }//GEN-LAST:event_menuSobreMouseClicked

    private void menuItemGerenciamentoAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciamentoAssuntoActionPerformed
        DialogGerenciadorAssunto telaAssunto = new DialogGerenciadorAssunto(this, true);
        telaAssunto.setVisible(true);
    }//GEN-LAST:event_menuItemGerenciamentoAssuntoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDevolução;
    private javax.swing.JButton btEmprestimo;
    private javax.swing.JButton btGerenciarObra;
    private javax.swing.JButton btGerenciarUsuario;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menuDevolução;
    private javax.swing.JMenu menuEmprestimo;
    private javax.swing.JMenu menuGerenciamento;
    private javax.swing.JMenuItem menuItemAutor;
    private javax.swing.JMenuItem menuItemEditora;
    private javax.swing.JMenuItem menuItemGerenciamentoAssunto;
    private javax.swing.JMenuItem menuItemObra;
    private javax.swing.JMenuItem menuItemOperador;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JLabel relogioDigital;
    // End of variables declaration//GEN-END:variables
}
